CREATE TABLE `ACCES2` (
  `PERE` char(1) DEFAULT NULL,
  `LIBELLE` varchar(150) DEFAULT NULL,
  KEY `PERE` (`PERE`)
); 

INSERT INTO ACCES2 VALUES ('A','à foyer ouvert');
INSERT INTO ACCES2 VALUES ('A','par ... abord …');
INSERT INTO ACCES2 VALUES ('A','par dissection ...');
INSERT INTO ACCES2 VALUES ('A','par excision de ...');
INSERT INTO ACCES2 VALUES ('A','par craniotomie');
INSERT INTO ACCES2 VALUES ('A','par craniocervicotomie');
INSERT INTO ACCES2 VALUES ('A','par cervicotomie');
INSERT INTO ACCES2 VALUES ('A','par cervicothoracotomie');
INSERT INTO ACCES2 VALUES ('A','par thoracotomie');
INSERT INTO ACCES2 VALUES ('A','par thoraco-phréno-laparotomie');
INSERT INTO ACCES2 VALUES ('A','par costotransversectomie');
INSERT INTO ACCES2 VALUES ('A','par laparotomie');
INSERT INTO ACCES2 VALUES ('A','par lombotomie');
INSERT INTO ACCES2 VALUES ('A','par périnéotomie');
INSERT INTO ACCES2 VALUES ('A','par arthrotomie');
INSERT INTO ACCES2 VALUES ('A','par colpotomie');
INSERT INTO ACCES2 VALUES ('A','par rectotomie');
INSERT INTO ACCES2 VALUES ('A','par sclérotomie');
INSERT INTO ACCES2 VALUES ('A','par -tomie');
INSERT INTO ACCES2 VALUES ('B','à foyer fermé');
INSERT INTO ACCES2 VALUES ('B','par injection intracaverneuse');
INSERT INTO ACCES2 VALUES ('B','par injection intradermique');
INSERT INTO ACCES2 VALUES ('B','par injection souscutanée');
INSERT INTO ACCES2 VALUES ('B','par injection transcutanée intralésionnelle');
INSERT INTO ACCES2 VALUES ('B','par injection transcutanée intratumorale ou péritumorale');
INSERT INTO ACCES2 VALUES ('B','par injection transmuqueuse');
INSERT INTO ACCES2 VALUES ('B','par ponction (transcutanée) de (organe)');
INSERT INTO ACCES2 VALUES ('B','par micro-incisions');
INSERT INTO ACCES2 VALUES ('B','par voie (…) transcutanée');
INSERT INTO ACCES2 VALUES ('B','par piqûre épidermique');
INSERT INTO ACCES2 VALUES ('B','par voie intramusculaire');
INSERT INTO ACCES2 VALUES ('B','par voie souscutanée');
INSERT INTO ACCES2 VALUES ('B','par voie stéréotaxique');
INSERT INTO ACCES2 VALUES ('B','par voie transcrânienne');
INSERT INTO ACCES2 VALUES ('B','par voie transfontanellaire');
INSERT INTO ACCES2 VALUES ('B','par voie transpérinéale');
INSERT INTO ACCES2 VALUES ('B','par voie transrectale');
INSERT INTO ACCES2 VALUES ('B','par voie transsclérale');
INSERT INTO ACCES2 VALUES ('B','par voie transsphénoïdale');
INSERT INTO ACCES2 VALUES ('B','par voie transtympanique');
INSERT INTO ACCES2 VALUES ('B','par voie transunguéale');
INSERT INTO ACCES2 VALUES ('B','par voie transvaginale');
INSERT INTO ACCES2 VALUES ('C','par arthoscopie');
INSERT INTO ACCES2 VALUES ('C','par cervicoscopie');
INSERT INTO ACCES2 VALUES ('C','par coelioscopie');
INSERT INTO ACCES2 VALUES ('C','par médiastinoscopie');
INSERT INTO ACCES2 VALUES ('C','par rétropéritonéoscopie');
INSERT INTO ACCES2 VALUES ('C','par thoracoscopie');
INSERT INTO ACCES2 VALUES ('C','par vidéochirurgie');
INSERT INTO ACCES2 VALUES ('C','par endoscopie transethmoïdale');
INSERT INTO ACCES2 VALUES ('D','par voie intracavitaire');
INSERT INTO ACCES2 VALUES ('D','par voie nasale');
INSERT INTO ACCES2 VALUES ('D','par voie buccale');
INSERT INTO ACCES2 VALUES ('D','par voie oesophagienne');
INSERT INTO ACCES2 VALUES ('D','par voie anale');
INSERT INTO ACCES2 VALUES ('D','par voie utérine');
INSERT INTO ACCES2 VALUES ('D','par voie vaginale');
INSERT INTO ACCES2 VALUES ('D','par voie naturelle');
INSERT INTO ACCES2 VALUES ('D','par cathétérisme urétral');
INSERT INTO ACCES2 VALUES ('D','par une -stomie déjà en place');
INSERT INTO ACCES2 VALUES ('E','par endoscopie (...)');
INSERT INTO ACCES2 VALUES ('E','par fibroscopie');
INSERT INTO ACCES2 VALUES ('E','par laryngoscopie (...)');
INSERT INTO ACCES2 VALUES ('E','par bronchoscopie au tube rigide');
INSERT INTO ACCES2 VALUES ('E','par oeso-gastro-duodénoscopie');
INSERT INTO ACCES2 VALUES ('E','par jéjunoscopie');
INSERT INTO ACCES2 VALUES ('E','par iléoscopie');
INSERT INTO ACCES2 VALUES ('E','par coloscopie …');
INSERT INTO ACCES2 VALUES ('E','par rectosigmoïdoscopie');
INSERT INTO ACCES2 VALUES ('E','par cholangioscopie rétrograde');
INSERT INTO ACCES2 VALUES ('E','par néphroscopie par une néphrostomie déjà en place');
INSERT INTO ACCES2 VALUES ('E','par urétéroscopie antérograde par une néphrostomie déjà en place');
INSERT INTO ACCES2 VALUES ('E','par urétéroscopie rétrograde');
INSERT INTO ACCES2 VALUES ('E','par urétrocystoscopie');
INSERT INTO ACCES2 VALUES ('E','par urétroscopie');
INSERT INTO ACCES2 VALUES ('E','par hystéroscopie');
INSERT INTO ACCES2 VALUES ('E','par colposcopie');
INSERT INTO ACCES2 VALUES ('E','par vaginoscopie');
INSERT INTO ACCES2 VALUES ('F','par hémodiafiltration, hémofiltration ou biofiltration');
INSERT INTO ACCES2 VALUES ('F','par hémodialyse');
INSERT INTO ACCES2 VALUES ('F','par hémoperfusion');
INSERT INTO ACCES2 VALUES ('F','par injection intraartérielle transcutanée');
INSERT INTO ACCES2 VALUES ('F','par injection intravasculaire transcutanée');
INSERT INTO ACCES2 VALUES ('F','par injection intraveineuse transcutanée');
INSERT INTO ACCES2 VALUES ('F','par ponction du cordon ombilical');
INSERT INTO ACCES2 VALUES ('F','par ponction transcutanée (d''un conduit) (d''un organe creux)');
INSERT INTO ACCES2 VALUES ('F','par perfusion');
INSERT INTO ACCES2 VALUES ('F','par un dispositif d''accès veineux');
INSERT INTO ACCES2 VALUES ('F','par voie artérielle transcutanée');
INSERT INTO ACCES2 VALUES ('F','par voie vasculaire transcutanée');
INSERT INTO ACCES2 VALUES ('F','par voie veineuse transcutanée');
INSERT INTO ACCES2 VALUES ('G','-scopie, par voie transcutanée');
INSERT INTO ACCES2 VALUES ('G','par néphroscopie transcutanée');
INSERT INTO ACCES2 VALUES ('G','par urétéroscopie antérograde           transcutanée');
INSERT INTO ACCES2 VALUES ('H','avec contrôle radiologique');
INSERT INTO ACCES2 VALUES ('H','avec guidage radiologique');
INSERT INTO ACCES2 VALUES ('H','avec guidage scanographique');
INSERT INTO ACCES2 VALUES ('H','avec ingestion de produit de contraste');
INSERT INTO ACCES2 VALUES ('H','avec injection de produit de contraste');
INSERT INTO ACCES2 VALUES ('H','par injection de produit de contraste');
INSERT INTO ACCES2 VALUES ('J','avec guidage échographique');
INSERT INTO ACCES2 VALUES ('J','avec guidage remnographique [IRM]');
INSERT INTO ACCES2 VALUES ('K','par radiographie');
INSERT INTO ACCES2 VALUES ('K','par radiologie');
INSERT INTO ACCES2 VALUES ('L','Curiethérapie');
INSERT INTO ACCES2 VALUES ('L','Irradiation externe');
INSERT INTO ACCES2 VALUES ('L','Scintigraphie');
INSERT INTO ACCES2 VALUES ('L','par radio-isotope');
INSERT INTO ACCES2 VALUES ('L','par méthode radio-isotopique');
INSERT INTO ACCES2 VALUES ('L','- radio-isotopique');
INSERT INTO ACCES2 VALUES ('M','Échographie (-doppler) transfontanellaire');
INSERT INTO ACCES2 VALUES ('M','Échographie (-doppler) transcrânienne');
INSERT INTO ACCES2 VALUES ('M','Échographie (-doppler) transcutanée');
INSERT INTO ACCES2 VALUES ('M','Échographie (-doppler) transthoracique');
INSERT INTO ACCES2 VALUES ('M','par échocardiographie transthoracique');
INSERT INTO ACCES2 VALUES ('M','par doppler … transcrânien');
INSERT INTO ACCES2 VALUES ('M','par doppler … transcutané');
INSERT INTO ACCES2 VALUES ('N','Remnographie [IRM]');
INSERT INTO ACCES2 VALUES ('N','par résonance magnétique cérébrale');
INSERT INTO ACCES2 VALUES ('N','par remnographie [IRM]');
INSERT INTO ACCES2 VALUES ('P','réalisation d''un acte utilisant d''autre moyen, sans accès, ou sans précision sur ses modalités');
