CREATE TABLE `CODE_PAIEMENT` (
  `CODE` char(1) NOT NULL DEFAULT '',
  `LIBELLE` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO CODE_PAIEMENT VALUES ('1','Seance');
INSERT INTO CODE_PAIEMENT VALUES ('2','Mois');
INSERT INTO CODE_PAIEMENT VALUES ('3','Trimestre');
INSERT INTO CODE_PAIEMENT VALUES ('4','Semestre');
INSERT INTO CODE_PAIEMENT VALUES ('5','Annee');
INSERT INTO CODE_PAIEMENT VALUES ('6','En une seule fois');
