CREATE TABLE `COMPAT_EXO_TM` (
  `EXOTM` char(1) NOT NULL DEFAULT '',
  `EXOTMCOMPAT` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`EXOTM`)
); 

INSERT INTO COMPAT_EXO_TM VALUES ('1','7');
INSERT INTO COMPAT_EXO_TM VALUES ('2','7');
INSERT INTO COMPAT_EXO_TM VALUES ('3','7');
INSERT INTO COMPAT_EXO_TM VALUES ('4','7');
INSERT INTO COMPAT_EXO_TM VALUES ('5','7');
