CREATE TABLE `DMT` (
  `CODE` char(3) NOT NULL DEFAULT '',
  `LIBELLE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO DMT VALUES ('35','DMT SCAN');
INSERT INTO DMT VALUES ('750','DMT TEP');
INSERT INTO DMT VALUES ('753','DMT IRM');
