CREATE TABLE `DOM` (
  `CODE` char(3) NOT NULL DEFAULT '',
  `LIBELLE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO DOM VALUES ('971','GUADELOUPE');
INSERT INTO DOM VALUES ('972','MARTINIQUE');
INSERT INTO DOM VALUES ('973','GUYANE');
INSERT INTO DOM VALUES ('974','REUNION');
