CREATE TABLE `EXT_DOC` (
  `CODE` char(1) NOT NULL DEFAULT '',
  `LIBELLE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO EXT_DOC VALUES ('A','Extension A');
INSERT INTO EXT_DOC VALUES ('B','Extension B');
INSERT INTO EXT_DOC VALUES ('C','Extension C');
