CREATE TABLE `PHASE` (
  `CODE` char(1) NOT NULL DEFAULT '',
  `LIBELLE` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO PHASE VALUES ('0','Phase par defaut');
INSERT INTO PHASE VALUES ('1','Phase 1');
INSERT INTO PHASE VALUES ('2','Phase 2');
INSERT INTO PHASE VALUES ('3','Phase 3');
