CREATE TABLE `TB17` (
  `SERIE` int(11) NOT NULL AUTO_INCREMENT,
  `PRESTATION` char(3) DEFAULT NULL,
  `SPECIALITE` char(2) DEFAULT NULL,
  `DATE_OBLIG` char(8) DEFAULT NULL,
  PRIMARY KEY (`SERIE`)
); 

INSERT INTO TB17 VALUES ('31','KCC','21','20050701');
