CREATE TABLE `TOPOGRAPHIE2` (
  `CODE` char(2) NOT NULL DEFAULT '',
  `PERE` char(1) DEFAULT NULL,
  `LIBELLE` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`CODE`),
  KEY `PERE` (`PERE`)
); 

INSERT INTO TOPOGRAPHIE2 VALUES ('AA','A','Encéphale');
INSERT INTO TOPOGRAPHIE2 VALUES ('AB','A','Ventricules, méninges et liquide cérébrospinal intracrâniens');
INSERT INTO TOPOGRAPHIE2 VALUES ('AC','A','Intracrânien, localisations multiples ou sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('AD','A','Nerfs crâniens');
INSERT INTO TOPOGRAPHIE2 VALUES ('AE','A','Moelle épinière');
INSERT INTO TOPOGRAPHIE2 VALUES ('AF','A','Canal de l''épendyme, méninges et liquide cérébrospinal rachidiens');
INSERT INTO TOPOGRAPHIE2 VALUES ('AG','A','Système nerveux central, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('AH','A','Nerfs rachidiens (y compris la partie intrarachidienne)');
INSERT INTO TOPOGRAPHIE2 VALUES ('AJ','A','Système nerveux autonome');
INSERT INTO TOPOGRAPHIE2 VALUES ('AK','A','Mémoire');
INSERT INTO TOPOGRAPHIE2 VALUES ('AL','A','Psychologie, cognition');
INSERT INTO TOPOGRAPHIE2 VALUES ('AM','A','Sommeil');
INSERT INTO TOPOGRAPHIE2 VALUES ('AN','A','Sensibilité, douleur');
INSERT INTO TOPOGRAPHIE2 VALUES ('AZ','A','Système nerveux, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('BA','B','Paupières, sourcils');
INSERT INTO TOPOGRAPHIE2 VALUES ('BB','B','Appareil lacrymal');
INSERT INTO TOPOGRAPHIE2 VALUES ('BC','B','Conjonctive bulbaire');
INSERT INTO TOPOGRAPHIE2 VALUES ('BD','B','Cornée');
INSERT INTO TOPOGRAPHIE2 VALUES ('BE','B','Iris, corps ciliaires, sclérotique, chambre antérieure');
INSERT INTO TOPOGRAPHIE2 VALUES ('BF','B','Cristallin');
INSERT INTO TOPOGRAPHIE2 VALUES ('BG','B','Rétine, choroïde, vitré, segment postérieur');
INSERT INTO TOPOGRAPHIE2 VALUES ('BH','B','Bulbe oculaire');
INSERT INTO TOPOGRAPHIE2 VALUES ('BJ','B','Muscles oculomoteurs');
INSERT INTO TOPOGRAPHIE2 VALUES ('BK','B','Orbite');
INSERT INTO TOPOGRAPHIE2 VALUES ('BL','B','Vision');
INSERT INTO TOPOGRAPHIE2 VALUES ('BZ','B','Œil, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('CA','C','Oreille externe');
INSERT INTO TOPOGRAPHIE2 VALUES ('CB','C','Oreille moyenne');
INSERT INTO TOPOGRAPHIE2 VALUES ('CC','C','Oreille interne');
INSERT INTO TOPOGRAPHIE2 VALUES ('CD','C','Audition');
INSERT INTO TOPOGRAPHIE2 VALUES ('CE','C','Équilibre');
INSERT INTO TOPOGRAPHIE2 VALUES ('CZ','C','Oreille, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('DA','D','Myocarde, cavités et cloisons cardiaques');
INSERT INTO TOPOGRAPHIE2 VALUES ('DB','D','Valves cardiaques, endocarde');
INSERT INTO TOPOGRAPHIE2 VALUES ('DC','D','Péricarde');
INSERT INTO TOPOGRAPHIE2 VALUES ('DD','D','Artères coronaires');
INSERT INTO TOPOGRAPHIE2 VALUES ('DE','D','Système de conduction de l''excitation du cœur');
INSERT INTO TOPOGRAPHIE2 VALUES ('DF','D','Vaisseaux pulmonaires');
INSERT INTO TOPOGRAPHIE2 VALUES ('DG','D','Aorte');
INSERT INTO TOPOGRAPHIE2 VALUES ('DH','D','Veines caves');
INSERT INTO TOPOGRAPHIE2 VALUES ('DK','D','Motricité cardiaque');
INSERT INTO TOPOGRAPHIE2 VALUES ('DZ','D','Cœur entier, cœur et gros vaisseaux, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('EA','E','Vaisseaux intracrâniens');
INSERT INTO TOPOGRAPHIE2 VALUES ('EB','E','Vaisseaux de la tête et du cou, extracrâniens ou non  précisé');
INSERT INTO TOPOGRAPHIE2 VALUES ('EC','E','Artères des membres supérieurs et du thorax');
INSERT INTO TOPOGRAPHIE2 VALUES ('ED','E','Artères abdominales et pelviennes');
INSERT INTO TOPOGRAPHIE2 VALUES ('EE','E','Artères des membres inférieurs');
INSERT INTO TOPOGRAPHIE2 VALUES ('EF','E','Veines des membres supérieurs et du thorax');
INSERT INTO TOPOGRAPHIE2 VALUES ('EG','E','Veines abdominales et pelviennes');
INSERT INTO TOPOGRAPHIE2 VALUES ('EH','E','Veine porte et ses branches');
INSERT INTO TOPOGRAPHIE2 VALUES ('EJ','E','Veines des membres inférieurs');
INSERT INTO TOPOGRAPHIE2 VALUES ('EK','E','Vaisseaux non précisés des membres supérieurs et du thorax');
INSERT INTO TOPOGRAPHIE2 VALUES ('EL','E','Vaisseaux non précisés abdominaux et pelviens');
INSERT INTO TOPOGRAPHIE2 VALUES ('EM','E','Vaisseaux non précisés des membres inférieurs');
INSERT INTO TOPOGRAPHIE2 VALUES ('EN','E','Artères, sans précisioon');
INSERT INTO TOPOGRAPHIE2 VALUES ('EP','E','Veines, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('EQ','E','Circulation sanguine');
INSERT INTO TOPOGRAPHIE2 VALUES ('EZ','E','Vaisseaux sanguins, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('FA','F','Tonsilles palatines et pharyngiennes');
INSERT INTO TOPOGRAPHIE2 VALUES ('FB','F','Thymus');
INSERT INTO TOPOGRAPHIE2 VALUES ('FC','F','Vaisseaux et nœuds lymphatiques');
INSERT INTO TOPOGRAPHIE2 VALUES ('FD','F','Moelle osseuse');
INSERT INTO TOPOGRAPHIE2 VALUES ('FE','F','Sang');
INSERT INTO TOPOGRAPHIE2 VALUES ('FF','F','Rate');
INSERT INTO TOPOGRAPHIE2 VALUES ('FG','F','Immunité');
INSERT INTO TOPOGRAPHIE2 VALUES ('FZ','F','Système hématopoïétique et réticuloendothélial, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('GA','G','Nez');
INSERT INTO TOPOGRAPHIE2 VALUES ('GB','G','Sinus paranasaux');
INSERT INTO TOPOGRAPHIE2 VALUES ('GC','G','Rhinopharynx et fosse infratemporale');
INSERT INTO TOPOGRAPHIE2 VALUES ('GD','G','Larynx et épiglotte');
INSERT INTO TOPOGRAPHIE2 VALUES ('GE','G','Trachée et arbre bronchique');
INSERT INTO TOPOGRAPHIE2 VALUES ('GF','G','Poumons');
INSERT INTO TOPOGRAPHIE2 VALUES ('GG','G','Plèvre');
INSERT INTO TOPOGRAPHIE2 VALUES ('GH','G','Espace médiastinal');
INSERT INTO TOPOGRAPHIE2 VALUES ('GJ','G','Odorat');
INSERT INTO TOPOGRAPHIE2 VALUES ('GK','G','Langage, phonation');
INSERT INTO TOPOGRAPHIE2 VALUES ('GL','G','Respiration');
INSERT INTO TOPOGRAPHIE2 VALUES ('GZ','G','Système respiratoire, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('HA','H','Lèvres, langue, cavité orale dans son ensemble');
INSERT INTO TOPOGRAPHIE2 VALUES ('HB','H','Dents, parodonte, gencives');
INSERT INTO TOPOGRAPHIE2 VALUES ('HC','H','Glandes salivaires');
INSERT INTO TOPOGRAPHIE2 VALUES ('HD','H','Oropharynx, voile du palais');
INSERT INTO TOPOGRAPHIE2 VALUES ('HE','H','Œsophage');
INSERT INTO TOPOGRAPHIE2 VALUES ('HF','H','Estomac');
INSERT INTO TOPOGRAPHIE2 VALUES ('HG','H','Intestin grêle');
INSERT INTO TOPOGRAPHIE2 VALUES ('HH','H','Côlon et appendice');
INSERT INTO TOPOGRAPHIE2 VALUES ('HJ','H','Rectum');
INSERT INTO TOPOGRAPHIE2 VALUES ('HK','H','Anus, régions anale et périanale');
INSERT INTO TOPOGRAPHIE2 VALUES ('HL','H','Foie');
INSERT INTO TOPOGRAPHIE2 VALUES ('HM','H','Vésicule et conduits biliaires');
INSERT INTO TOPOGRAPHIE2 VALUES ('HN','H','Pancréas');
INSERT INTO TOPOGRAPHIE2 VALUES ('HP','H','Péritoine et cavité péritonéale');
INSERT INTO TOPOGRAPHIE2 VALUES ('HQ','H','Déglutition');
INSERT INTO TOPOGRAPHIE2 VALUES ('HR','H','Digestion');
INSERT INTO TOPOGRAPHIE2 VALUES ('HS','H','Nutrition');
INSERT INTO TOPOGRAPHIE2 VALUES ('HT','H','Défécation');
INSERT INTO TOPOGRAPHIE2 VALUES ('HZ','H','Système digestif, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('JA','J','Rein');
INSERT INTO TOPOGRAPHIE2 VALUES ('JB','J','Bassinet et jonction pyélo-urétérale');
INSERT INTO TOPOGRAPHIE2 VALUES ('JC','J','Uretère');
INSERT INTO TOPOGRAPHIE2 VALUES ('JD','J','Vessie');
INSERT INTO TOPOGRAPHIE2 VALUES ('JE','J','Urètre');
INSERT INTO TOPOGRAPHIE2 VALUES ('JF','J','Espace rétropéritonéal et souspéritonéal');
INSERT INTO TOPOGRAPHIE2 VALUES ('JG','J','Prostate, vésicules séminales');
INSERT INTO TOPOGRAPHIE2 VALUES ('JH','J','Scrotum, contenu scrotal, pénis');
INSERT INTO TOPOGRAPHIE2 VALUES ('JJ','J','Ovaire, trompe');
INSERT INTO TOPOGRAPHIE2 VALUES ('JK','J','Utérus non gravide');
INSERT INTO TOPOGRAPHIE2 VALUES ('JL','J','Vagin');
INSERT INTO TOPOGRAPHIE2 VALUES ('JM','J','Vulve, périnée féminin');
INSERT INTO TOPOGRAPHIE2 VALUES ('JN','J','Utérus gravide');
INSERT INTO TOPOGRAPHIE2 VALUES ('JP','J','Placenta, amnios, cordon');
INSERT INTO TOPOGRAPHIE2 VALUES ('JQ','J','Fœtus, embryon');
INSERT INTO TOPOGRAPHIE2 VALUES ('JR','J','Miction');
INSERT INTO TOPOGRAPHIE2 VALUES ('JS','J','Fécondation');
INSERT INTO TOPOGRAPHIE2 VALUES ('JT','J','Sexualité, érection');
INSERT INTO TOPOGRAPHIE2 VALUES ('JV','J','Sécrétion urinaire, épuration sanguine');
INSERT INTO TOPOGRAPHIE2 VALUES ('JZ','J','Appareil urinaire et génital, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('KA','K','Hypophyse');
INSERT INTO TOPOGRAPHIE2 VALUES ('KB','K','Épiphyse');
INSERT INTO TOPOGRAPHIE2 VALUES ('KC','K','Glande thyroïde');
INSERT INTO TOPOGRAPHIE2 VALUES ('KD','K','Glandes parathyroïdes');
INSERT INTO TOPOGRAPHIE2 VALUES ('KE','K','Glandes surrénales');
INSERT INTO TOPOGRAPHIE2 VALUES ('KF','K','Tumeur parapharyngée');
INSERT INTO TOPOGRAPHIE2 VALUES ('KG','K','Métabolisme');
INSERT INTO TOPOGRAPHIE2 VALUES ('KZ','K','Système endocrinien, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('LA','L','Squelette du crâne, de la face ou sans précision (sauf mâchoire)');
INSERT INTO TOPOGRAPHIE2 VALUES ('LB','L','Maxillaire, mandibule');
INSERT INTO TOPOGRAPHIE2 VALUES ('LC','L','Muscles et tissus mous du crâne, de la face et du cou  (sauf muscles oculomoteurs)');
INSERT INTO TOPOGRAPHIE2 VALUES ('LD','L','Colonne vertébrale cervicale, charnières vertébrooccipitale et cervicothoracique');
INSERT INTO TOPOGRAPHIE2 VALUES ('LE','L','Colonne vertébrale thoracique, charnière thoracolombaire');
INSERT INTO TOPOGRAPHIE2 VALUES ('LF','L','Colonne vertébrale lombaire, charnière lombosacrée');
INSERT INTO TOPOGRAPHIE2 VALUES ('LG','L','Sacrum, coccyx');
INSERT INTO TOPOGRAPHIE2 VALUES ('LH','L','Colonne vertébrale, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('LJ','L','Cage thoracique');
INSERT INTO TOPOGRAPHIE2 VALUES ('LL','L','Muscles et tissus mous de la paroi thoracique. Diaphragme');
INSERT INTO TOPOGRAPHIE2 VALUES ('LM','L','Muscles et tissus mous des parois abdominale et lombaire');
INSERT INTO TOPOGRAPHIE2 VALUES ('LZ','L','Os, articulations et tissus mous de la tête, du cou et du tronc, localisations multiples ou sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('MA','M','Scapula, clavicule');
INSERT INTO TOPOGRAPHIE2 VALUES ('MB','M','Humérus');
INSERT INTO TOPOGRAPHIE2 VALUES ('MC','M','Os de l''avant-bras');
INSERT INTO TOPOGRAPHIE2 VALUES ('MD','M','Os de la main');
INSERT INTO TOPOGRAPHIE2 VALUES ('ME','M','Articulations de la ceinture scapulaire');
INSERT INTO TOPOGRAPHIE2 VALUES ('MF','M','Articulations du coude');
INSERT INTO TOPOGRAPHIE2 VALUES ('MG','M','Articulations du poignet');
INSERT INTO TOPOGRAPHIE2 VALUES ('MH','M','Articulations de la main');
INSERT INTO TOPOGRAPHIE2 VALUES ('MJ','M','Muscles et tissus mous du membre supérieur');
INSERT INTO TOPOGRAPHIE2 VALUES ('MK','M','Préhension');
INSERT INTO TOPOGRAPHIE2 VALUES ('MZ','M','Os, articulations et tissus mous du membre supérieur, localisations multiples ou sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('NA','N','Os coxal');
INSERT INTO TOPOGRAPHIE2 VALUES ('NB','N','Fémur et patelle');
INSERT INTO TOPOGRAPHIE2 VALUES ('NC','N','Os de la jambe');
INSERT INTO TOPOGRAPHIE2 VALUES ('ND','N','Os du pied');
INSERT INTO TOPOGRAPHIE2 VALUES ('NE','N','Articulations de la ceinture pelvienne, articulation coxofémorale');
INSERT INTO TOPOGRAPHIE2 VALUES ('NF','N','Articulation du genou');
INSERT INTO TOPOGRAPHIE2 VALUES ('NG','N','Articulations de la cheville');
INSERT INTO TOPOGRAPHIE2 VALUES ('NH','N','Articulations du pied');
INSERT INTO TOPOGRAPHIE2 VALUES ('NJ','N','Muscles et tissus mous du membre inférieur');
INSERT INTO TOPOGRAPHIE2 VALUES ('NK','N','Marche');
INSERT INTO TOPOGRAPHIE2 VALUES ('NZ','N','Os, articulations et tissus mous du membre inférieur, localisations multiples ou sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('PA','P','Os, sans mention de localisation');
INSERT INTO TOPOGRAPHIE2 VALUES ('PB','P','Articulations, sans mention de localisation');
INSERT INTO TOPOGRAPHIE2 VALUES ('PC','P','Muscles, sans mention de localisation');
INSERT INTO TOPOGRAPHIE2 VALUES ('PD','P','Tissus mous, sans mention de localisation');
INSERT INTO TOPOGRAPHIE2 VALUES ('PE','P','Mobilité, tonicité');
INSERT INTO TOPOGRAPHIE2 VALUES ('PZ','P','Os, articulations et tissus mous, localisations multiples sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('QA','Q','Peau et tissu cellulaire souscutané  de la tête et du cou');
INSERT INTO TOPOGRAPHIE2 VALUES ('QB','Q','Peau et tissu cellulaire souscutané  du tronc');
INSERT INTO TOPOGRAPHIE2 VALUES ('QC','Q','Peau et tissu cellulaire souscutané  du membre supérieur');
INSERT INTO TOPOGRAPHIE2 VALUES ('QD','Q','Peau et tissu cellulaire souscutané  du membre inférieur');
INSERT INTO TOPOGRAPHIE2 VALUES ('QE','Q','Sein');
INSERT INTO TOPOGRAPHIE2 VALUES ('QZ','Q','Peau et tissu cellulaire souscutané, sans précision');
INSERT INTO TOPOGRAPHIE2 VALUES ('ZA','Z','Tête et cou');
INSERT INTO TOPOGRAPHIE2 VALUES ('ZB','Z','Thorax');
INSERT INTO TOPOGRAPHIE2 VALUES ('ZC','Z','Abdomen et petit bassin');
INSERT INTO TOPOGRAPHIE2 VALUES ('ZD','Z','Membre supérieur');
INSERT INTO TOPOGRAPHIE2 VALUES ('ZE','Z','Membre inférieur');
INSERT INTO TOPOGRAPHIE2 VALUES ('ZF','Z','Qualité de la vie');
INSERT INTO TOPOGRAPHIE2 VALUES ('ZZ','Z','Région topographique non précisée');
