CREATE TABLE `TOPOGRAPHIE1` (
  `CODE` char(1) NOT NULL DEFAULT '',
  `LIBELLE` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO TOPOGRAPHIE1 VALUES ('A','SYST»ME NERVEUX');
INSERT INTO TOPOGRAPHIE1 VALUES ('B','OEIL');
INSERT INTO TOPOGRAPHIE1 VALUES ('C','OREILLE');
INSERT INTO TOPOGRAPHIE1 VALUES ('D','COEUR ET GROS VAISSEAUX');
INSERT INTO TOPOGRAPHIE1 VALUES ('E','VAISSEAUX P…RIPH…RIQUES');
INSERT INTO TOPOGRAPHIE1 VALUES ('F','SYST»ME H…MATOPOœ…TIQUE ET R…TICULOENDOTH…LIAL');
INSERT INTO TOPOGRAPHIE1 VALUES ('G','SYST»ME RESPIRATOIRE');
INSERT INTO TOPOGRAPHIE1 VALUES ('H','SYST»ME DIGESTIF');
INSERT INTO TOPOGRAPHIE1 VALUES ('J','APPAREIL URINAIRE ET G…NITAL, PROCR…ATION');
INSERT INTO TOPOGRAPHIE1 VALUES ('K','SYST»ME ENDOCRINIEN');
INSERT INTO TOPOGRAPHIE1 VALUES ('L','OS, ARTICULATIONS & TISSUS MOUS : T TE, COU ET TRONC');
INSERT INTO TOPOGRAPHIE1 VALUES ('M','OS, ARTICULATIONS & TISSUS MOUS : MEMBRE SUP…RIEUR');
INSERT INTO TOPOGRAPHIE1 VALUES ('N','OS, ARTICULATIONS & TISSUS MOUS : MEMBRE INF…RIEUR');
INSERT INTO TOPOGRAPHIE1 VALUES ('P','OS, ARTICULATIONS & TISSUS MOUS : LOCALISAT. IMPR…CISE');
INSERT INTO TOPOGRAPHIE1 VALUES ('Q','PEAU ET TISSU CELLULAIRE SOUSCUTAN…');
INSERT INTO TOPOGRAPHIE1 VALUES ('Z','R…GIONS TOPOGRAPHIQUES');
