CREATE TABLE `TYPE_FORFAIT` (
  `CODE` char(1) NOT NULL DEFAULT '',
  `LIBELLE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO TYPE_FORFAIT VALUES ('1','Forfait SCAN');
INSERT INTO TYPE_FORFAIT VALUES ('2','Forfait IRM');
INSERT INTO TYPE_FORFAIT VALUES ('3','Forfait TEP');
INSERT INTO TYPE_FORFAIT VALUES ('4','Forfait Vidéocapsule');
INSERT INTO TYPE_FORFAIT VALUES ('5','Forfait Sécurité Dermatologie');
