CREATE TABLE `VAL_UNITE_OEUVRE` (
  `CODE` char(3) NOT NULL DEFAULT '',
  `DATEEFFET` char(8) DEFAULT NULL,
  `VALEUR` decimal(6,2) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
); 

INSERT INTO VAL_UNITE_OEUVRE VALUES ('5.3','20050325','5.30');
