CREATE TABLE `VERSION` (
  `SERIE` int(11) NOT NULL AUTO_INCREMENT,
  `IDFICHIER` char(3) DEFAULT NULL,
  `DATECREATION` char(8) DEFAULT NULL,
  `DATEINTEGRATION` char(8) DEFAULT NULL,
  `CHRONOLOGIE` char(5) DEFAULT NULL,
  `TYPEFICHIER` char(1) DEFAULT NULL,
  `NUMVERSION` char(4) DEFAULT NULL,
  PRIMARY KEY (`SERIE`)
); 

INSERT INTO VERSION VALUES ('11','CAC','20140605','20140822','00037','1','0301');
